import type { NextPage, GetServerSideProps } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Navbar from '../components/navbar/navbar';
import Footer from '../components/footer/footer';
import List from '../components/list/list';
import styles from '../styles/Home.module.css';
import 'isomorphic-fetch';
import {
    ALL_POSTS,
    BASE_URL,
    isEmpty,
    serializeQuery,
    SUBREDDIT_PATH,
    SUFFIX,
} from '../utils';

interface IProps {
    postRes: models.IRedditResponse;
    subreddit: string;
}

const DEFAULT_POST_LIMIT = 10;

export const getServerSideProps: GetServerSideProps = async (context) => {
    const query = context.query;
    let subreddit = query.s;
    if (isEmpty(subreddit)) {
        subreddit = ALL_POSTS;
    }

    if (isEmpty(query.limit)) {
        query.limit = DEFAULT_POST_LIMIT.toString();
    }

    delete query.s;

    try {


        const response = await fetch(
            `${BASE_URL}${SUBREDDIT_PATH}${subreddit}${SUFFIX}${serializeQuery(
                query
            )}`
        );

        const jres: models.IRedditResponse = await response.json();

        return {
            props: {
                postRes: jres,
                subreddit
            },
        };
    } catch (error) {
        return {
            props: {
                postRes: null,
                subreddit
            },
        };
    }
};

const Home: NextPage<IProps> = ({ postRes, subreddit }: IProps) => {
    // const [posts, setPosts] = useState([] as models.IRedditPost[]);
    // const getPosts = async () => {
    //   try {
    //     const res = await fetch('/api/reddit');
    //     const redditResponse: models.IRedditResponse = await res.json();
    //     setPosts(redditResponse.data.children);

    //   } catch (error) {
    //     console.log(error)
    //   }
    // };

    // useEffect(() => {
    //   getPosts();
    // }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>subReddit</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="relative bg-gray-200 pt-24 lg:pt-28 pb-16 min-h-screen">
                <main>
                    <div className='absolute top-20 text-xs w-full text-center font-bold'>
                        <span>{!isEmpty(subreddit) && subreddit !== ALL_POSTS ? `/r/${subreddit}` : ''}</span>
                    </div>
                    <List posts={postRes?.data?.children} />
                </main>
                <Footer />
            </div>
        </div>
    );
};

export default Home;
